export const UPDATEMESSAGELIST = 'UPDATEMESSAGELIST';
export const CLEARMESSAGELIST = 'CLEARMESSAGELIST';

export const RETURNCONVERSATION = 'RETURNCONVERSATION';
export const CLEARCONVERSATION = 'CLEARCONVERSATION';

export const UPDATEEPISODE = 'UPDATEEPISODE';
