export const UPDATEMESSAGELIST = 'UPDATEMESSAGELIST';
export const CLEARMESSAGELIST = 'CLEARMESSAGELIST';

export const RETURNCONVERSATION = 'RETURNCONVERSATION';
export const CLEARCONVERSATION = 'CLEARCONVERSATION';
export const SETCURRENTSTEP = 'SETCURRENTSTEP';
export const INCREASESTEP = 'INCREASESTEP';
export const SETKEY = 'SETKEY';

export const UPDATEEPISODE = 'UPDATEEPISODE';

export const ASKQUESTION = 'ASKQUESTION';

export const CALLARRAY = 'CALLARRAY';
